# Generated by Django 4.2.1 on 2023-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('media', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('media', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('media', models.FileField(upload_to='images/')),
            ],
        ),
    ]
