# Generated by Django 4.2.1 on 2023-06-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_collectioncarousel_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncarousel',
            name='large_file',
            field=models.FileField(default=None, upload_to='static/videos/'),
        ),
        migrations.AlterField(
            model_name='collectioncarousel',
            name='small_file',
            field=models.FileField(default=None, upload_to='static/videos/'),
        ),
        migrations.AlterField(
            model_name='productcarousel',
            name='large_file',
            field=models.FileField(default=None, upload_to='static/videos/'),
        ),
        migrations.AlterField(
            model_name='productcarousel',
            name='small_file',
            field=models.FileField(default=None, upload_to='static/videos/'),
        ),
        migrations.AlterField(
            model_name='promotioncarousel',
            name='large_file',
            field=models.FileField(default=None, upload_to='static/videos/'),
        ),
        migrations.AlterField(
            model_name='promotioncarousel',
            name='small_file',
            field=models.FileField(default=None, upload_to='static/videos/'),
        ),
    ]
