# Generated by Django 4.2.1 on 2023-05-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_collection_promotion_category_slug_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
